[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.25"
optimizer = true
optimizer_runs = 200
via_ir = true
auto_detect_solc = false
gas_reports = ["*"]
isolate = true
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "v4-core/=lib/v4-core/",
    "@uniswap/v4-core/=lib/v4-core/",
    "cofhe-mock/=lib/cofhe-mock-contracts/",
    "@fhenixprotocol/cofhe-contracts/=node_modules/@fhenixprotocol/cofhe-contracts/",
    "hardhat/=lib/forge-std/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
